local_planner:
  ros__parameters:
    generic:
      event_type: "autocross"  # Possible values: "acceleration" "autocross" "skidpad". overrided by launch file
      line_step: 0.5 # m
      circle_step: 0.1 # m
      debug: true

      topics:
        subscribers:
          race_status: "/planning/race_status"
          odometry: "/Odometry"
          slam_cones: "/slam/cones_positions"
        publishers:
          borders: "/planning/borders"
          center_line: "/planning/center_line"
          borders_completed: "/planning/borders_completed"
          center_line_completed: "/planning/center_line_completed"

    autocross:
      search_angle: 270.0 # degrees
      search_distance: 10.0 # m
      max_odom_distance: 15.0  # m
      debug_search_area_topic: "/planning/debug/search_area"

    acceleration:
      meters_over_horizon: 150.0
      safe_slope: 0.1 # if the slope is lower, we publish center_line_completed and we stop the node

    skidpad:
      center_x : 15.0 # m
      center_y : 9.125 # m
      inner_radius : 7.625 # m
      outer_radius : 10.625 # m
      max_distance_from_center: 5.0 # m # max dist from theoretical center
      radius_offset : 0.0 # m # tuned for the larger trajectory, 0.0 to revert
      end_x: 100.0 # m
      minimum_cones: 3 #minumum number of cones to start the process
